version: "3"
  
services:
  hflbesu:
     image: hyperledger/besu
     ports:
        - 8545:8545
        - 8546:8546
        - 30303:30303
     command: [
         "--rpc-http-enabled",
         "--host-allowlist=*"]
  nginx:
     image: nginx
     ports:
         - 80:8080
     volumes:
         - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
